---
title: "Chapter 7: Multiple testing"
author: "Matthias Kohl"
date: "October 2022"
output:
  rmarkdown::html_document:
    theme: united
    highlight: tango
    toc: true
---


```{r, eval=FALSE}
BiocManager::install(c("multtest", "limma", "ComplexHeatmap"), 
                     update = FALSE)
install.packages("MKomics")
```


```{r}
library(ggplot2)
library(MKpower)
library(multtest)
library(MKomics)
library(MKinfer)
```


## 7.1 Introduction


## 7.2 Family-wise Error Rate (FWER)

```{r}
N <- 1:150
FWER <- 100*(1 - (1-0.05)^N)
DF <- data.frame(N = N, FWER = FWER)
ggplot(DF, aes(x = N, y = FWER)) +
  geom_point() + geom_line() + xlab("Number of tests") + ylab("FWER [%]") + 
  ggtitle("FWER assuming independent tests")
```


```{r}
round(DF[c(1,2,3,5,10,14,45,59,90),], 1)
```


```{r}
pval <- c(0.004, 0.011, 0.039, 0.012, 0.001, 0.480)
p.adjust(pval, method = "bonferroni")
```


```{r}
## sorting not necessary
p.adjust(pval, method = "holm")
```


```{r}
## sorting not necessary
p.adjust(pval, method = "hochberg")
```


```{r}
## endpoint 1
power.welch.t.test(delta = 0.5, sd1 = 1.0, sd2 = 1.2, 
                   sig.level = 0.05/3, power = 0.9)
## endpoint 2
power.welch.t.test(delta = 0.75, sd1 = 1.5, sd2 = 1.2, 
                   sig.level = 0.05/3, power = 0.9)
## endpoint 3
power.welch.t.test(delta = 1.0, sd1 = 1.5, sd2 = 1.75, 
                   sig.level = 0.05/3, power = 0.9)
```


```{r}
## endpoint 2
power.welch.t.test(delta = 0.75, sd1 = 1.5, sd2 = 1.2, 
                   sig.level = 0.05/3, n = 134)
## endpoint 3
power.welch.t.test(delta = 1.0, sd1 = 1.5, sd2 = 1.75, 
                   sig.level = 0.05/3, n = 134)
```


## 7.3 False Discovery Rate (FDR)

```{r}
## Sorting not necessary
p.adjust(pval, method = "fdr")
```


```{r}
data(golub)
str(golub)
```


```{r}
golub.cl <- factor(golub.cl, labels = c("ALL", "AML"))
table(golub.cl)
```


```{r}
ttest <- function(x, g) t.test(x~g)[["p.value"]]
p.values <- apply(X = golub, MARGIN = 1, FUN = ttest, g = golub.cl)
```


```{r}
hist(p.values, nclass = 101, 
     main = "Histogram of the (unadjusted) p values")
```


```{r}
M <- matrix(rnorm(nrow(golub)*ncol(golub)), nrow = nrow(golub))
p.values.cf <- apply(M, 1, ttest, g = golub.cl)
```


```{r}
par(mfrow = c(2, 1))
hist(p.values, nclass = 101, xlab = "p value", main = "Golub data")
abline(h = 30.2)
hist(p.values.cf, nclass = 101, xlab = "p value", 
     main = "random numbers with no group difference")
abline(h = 30.2)
```


```{r}
## expected number
0.05*nrow(M)
## actual number
sum(p.values.cf < 0.05)
```


```{r}
sum(p.values < 0.05)
```


```{r}
p.values.adj <- mt.rawp2adjp(p.values)
```


```{r}
colSums(p.values.adj[["adjp"]] < 0.05)
```


```{r}
logFC <- apply(golub, 1, pairwise.logfc, g = golub.cl)
```


```{r}
volcano(x = logFC, pval = p.values.adj[["adjp"]][, "BH"], effect.low = -log10(2),
        effect.high = log10(2), alpha = 0.3, 
        xlab = expression(paste(log[10], "-fold change")), 
        ylab = expression(paste(-log[10], "(adj. p value)")), 
        title = "volcano plot")
```


## 7.4 Exercises
